# Generated by Django 5.1.7 on 2025-07-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_smsverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='phone number'),
        ),
    ]
