[pytest]
testpaths = tests


# Полезные опции по умолчанию:
addopts =
    -v


markers =
    unit: быстрые модульные тесты без БД и сети
    redeye: тесты провайдера Redeye

# Логи тестов сразу читаемые
log_cli = true
log_cli_level = INFO
log_cli_format = %(levelname)s %(name)s: %(message)s
