[pytest]
testpaths = tests
DJANGO_SETTINGS_MODULE = config.settings
cache_dir = .pytest_cache_local

pythonpath = .
    apps


addopts =
    -v


log_cli = true
log_cli_level = INFO
log_cli_format = %(levelname)s %(name)s: %(message)s
