# Generated by Django 5.1.7 on 2025-07-06 14:08

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('dollar_value', models.FloatField(default=80.0, verbose_name='Курс доллара к рублю')),
                ('dollar_auto_update', models.BooleanField(default=True, verbose_name='Автообновление Доллара')),
                ('euro_value', models.FloatField(default=100.0, verbose_name='Курс евро к рублю')),
                ('euro_auto_update', models.BooleanField(default=True, verbose_name='Автообновление Евро')),
            ],
            options={
                'verbose_name': 'Курс валют',
            },
        ),
    ]