# Generated by Django 5.1.7 on 2025-07-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="URL to track (YouTube)",
                max_length=512,
                null=True,
                verbose_name="Track URL",
            ),
        ),
    ]
