# Generated by Django 5.1.7 on 2025-07-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_track_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Barcode'),
        ),
    ]
