# Generated by Django 5.1.7 on 2025-08-24 14:09

import records.models

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0002_track_youtube_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="audio_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=records.models.track_upload_to,
                verbose_name="Audio",
            ),
        ),
    ]
