# Generated by Django 5.1.7 on 2025-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0003_alter_record_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="catalog_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Catalog number",
            ),
        ),
    ]
