# Generated by Django 5.1.7 on 2025-07-29 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0003_alter_order_options_order_notes_order_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="record",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
