# Generated by Django 5.1.7 on 2025-08-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_orderitem_order_remove_orderitem_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/'),
        ),
    ]
