# Generated by Django 5.1.7 on 2025-09-07 11:52

import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_orderitem_order_remove_orderitem_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=records.models.track_upload_to, verbose_name='Audio'),
        ),
    ]
