# Generated by Django 5.1.7 on 2025-09-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_orderitem_order_remove_orderitem_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='name',
            field=models.CharField(choices=[('not specified', 'Not specified'), ('7"', '7"'), ('10"', '10"'), ('12"', '12"'), ('EP', 'EP'), ('Single', 'Single'), ('LP', 'LP'), ('2LP', '2LP'), ('3LP', '3LP'), ('4LP', '4LP'), ('Box Set', 'Box Set'), ('Picture Disc', 'Picture Disc')], max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('not specified', 'Not specified'), ('House', 'House'), ('Techno', 'Techno'), ('Electro', 'Electro'), ('Breaks', 'Breaks'), ('Drum & Bass', 'Drum & Bass'), ('Garage', 'Garage'), ('Ambient', 'Ambient'), ('Experimental', 'Experimental'), ('Disco', 'Disco'), ('Hip-Hop', 'Hip-Hop'), ('Reggae', 'Reggae'), ('Dub', 'Dub'), ('Trance', 'Trance')], max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(choices=[('not specified', 'Not specified'), ('Deep House', 'Deep House'), ('Minimal', 'Minimal'), ('Acid', 'Acid'), ('Detroit', 'Detroit'), ('Progressive', 'Progressive'), ('Jungle', 'Jungle'), ('Breakbeat', 'Breakbeat'), ('UK Garage', 'UK Garage'), ('IDM', 'IDM'), ('Downtempo', 'Downtempo'), ('Lo-Fi', 'Lo-Fi'), ('Hardcore', 'Hardcore'), ('Italo', 'Italo'), ('Leftfield', 'Leftfield')], max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
