# Generated by Django 5.1.7 on 2025-10-16 12:33

import django.db.models.deletion
import records.models
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_format_name_alter_genre_name_alter_style_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('record', 'position_index', 'position'), 'verbose_name': 'Track', 'verbose_name_plural': 'Tracks'},
        ),
        migrations.AddField(
            model_name='record',
            name='is_expected',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Предзаказ (ожидается)'),
        ),
        migrations.AddField(
            model_name='record',
            name='release_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='День релиза'),
        ),
        migrations.AddField(
            model_name='record',
            name='release_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Месяц релиза'),
        ),
        migrations.AddField(
            model_name='track',
            name='audio_preview',
            field=models.FileField(blank=True, help_text='Local preview file stored in media (optional).', null=True, upload_to=records.models.PathByInstance('audio_preview'), verbose_name='mp3'),
        ),
        migrations.AddField(
            model_name='track',
            name='position_index',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Sequential order across the release (1..N), independent of sides.', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='format',
            name='name',
            field=models.CharField(choices=[('Not specified', 'Not specified'), ('7"', '7"'), ('10"', '10"'), ('12"', '12"'), ('EP', 'EP'), ('Single', 'Single'), ('LP', 'LP'), ('2LP', '2LP'), ('3LP', '3LP'), ('4LP', '4LP'), ('Box Set', 'Box Set'), ('Picture Disc', 'Picture Disc')], max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='record',
            name='cover_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=records.models.PathByInstance('cover_image'), verbose_name='Record image'),
        ),
        migrations.AlterField(
            model_name='record',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год релиза'),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(blank=True, help_text="Optional; e.g., '05:58'.", max_length=10, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='track',
            name='position',
            field=models.CharField(blank=True, help_text="Original position from the source (e.g., 'A1', 'B2'); may be empty.", max_length=10, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='track',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional preview/video URL (e.g., YouTube).', max_length=512, null=True, verbose_name='Track video URL'),
        ),
        migrations.CreateModel(
            name='RecordSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('redeye', 'Redeye'), ('discogs', 'Discogs'), ('juno', 'Juno')], help_text='Провайдер данных: redeye / discogs / juno и т.д.', max_length=24, verbose_name='Provider')),
                ('role', models.CharField(choices=[('product_page', 'Product page'), ('api', 'API'), ('listing', 'Listing')], default='product_page', help_text='Роль ссылки: product_page / api / listing.', max_length=24, verbose_name='Role')),
                ('url', models.URLField(help_text='Ссылка на внешний источник для этой записи.', verbose_name='Source URL')),
                ('can_fetch_audio', models.BooleanField(default=False, help_text='Можно ли пытаться собирать mp3-превью с этой страницы.', verbose_name='Can fetch audio previews')),
                ('last_audio_scrape_at', models.DateTimeField(blank=True, help_text='Когда последний раз пытались собрать mp3-ссылки с этой страницы.', null=True, verbose_name='Last audio scrape at')),
                ('audio_urls_count', models.PositiveIntegerField(default=0, help_text='Сколько mp3-ссылок нашли в прошлую попытку.', verbose_name='Audio URLs found (last scrape)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='records.record', verbose_name='Record')),
            ],
            options={
                'verbose_name': 'Record source',
                'verbose_name_plural': 'Record sources',
                'indexes': [models.Index(fields=['provider', 'role'], name='idx_source_provider_role'), models.Index(fields=['can_fetch_audio'], name='idx_source_can_fetch_audio')],
                'constraints': [models.UniqueConstraint(fields=('record', 'provider', 'role'), name='uq_recordsource_record_provider_role')],
            },
        ),
    ]
