# Generated by Django 5.2.8 on 2025-12-15 15:17

import records.models
import sorl.thumbnail.fields
from django.db import migrations, models, transaction


DEFAULT_FORMATS: tuple[str, ...] = (
    "Not specified",
    '7"',
    '10"',
    '12"',
    "EP",
    "Single",
    "LP",
    "2LP",
    "3LP",
    "4LP",
    "Box Set",
    "Picture Disc",
)

DEFAULT_GENRES: tuple[str, ...] = (
    "Not specified",
    "Jungle",
    "Drum and Bass",
    "Hardcore Breakbeat",
    "Breakbeat",
    "UK Garage",
    "Electro",
    "Dubstep",
    "Grime",
    "Bass",
    "Funk",
    "Disco",
    "House",
    "Reggae",
    "Dancehall",
    "Dub",
    "Dub Techno",
    "Techno",
    "Trance",
    "Ambient",
)


def seed_formats_and_genres(apps, schema_editor) -> None:
    Format = apps.get_model("records", "Format")
    Genre = apps.get_model("records", "Genre")
    using = schema_editor.connection.alias

    with transaction.atomic(using=using):
        for name in DEFAULT_FORMATS:
            Format.objects.using(using).get_or_create(name=name)

        for name in DEFAULT_GENRES:
            Genre.objects.using(using).get_or_create(name=name)


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0005_alter_track_options_record_is_expected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="format",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="record",
            name="artists",
            field=models.ManyToManyField(
                related_name="records", to="records.artist", verbose_name="Исполнитель"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="condition",
            field=models.CharField(
                choices=[
                    ("НОВАЯ", "НОВАЯ"),
                    ("M", "Mint (M)"),
                    ("NM", "Near Mint (NM)"),
                    ("VG+", "Very Good Plus (VG+)"),
                    ("VG", "Very Good (VG)"),
                    ("G+", "Good Plus (G+)"),
                    ("G", "Good (G)"),
                    ("F", "Fair (F)"),
                    ("P", "Poor (P)"),
                ],
                default="M",
                max_length=10,
                verbose_name="Состояние",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="cover_image",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                null=True,
                upload_to=records.models.PathByInstance("cover_image"),
                verbose_name="Обложка",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="formats",
            field=models.ManyToManyField(
                related_name="records", to="records.format", verbose_name="Форматы"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="genres",
            field=models.ManyToManyField(
                related_name="records", to="records.genre", verbose_name="Жанры"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="styles",
            field=models.ManyToManyField(
                related_name="records", to="records.style", verbose_name="Стили"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        # Засев справочников (идемпотентно).
        migrations.RunPython(
            seed_formats_and_genres,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
