# Generated by Django 5.1.7 on 2025-09-30 15:44

import records.models
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_seed_presets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='cover_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=records.models.record_upload_to, verbose_name='Record image'),
        ),
        migrations.AlterField(
            model_name='track',
            name='position',
            field=models.CharField(blank=True, max_length=10, verbose_name='Position'),
        ),
    ]
