# Generated by Django 5.1.7 on 2025-09-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_record_cover_image_alter_track_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_expected',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Предзаказ (ожидается)'),
        ),
        migrations.AddField(
            model_name='record',
            name='release_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='День релиза'),
        ),
        migrations.AddField(
            model_name='record',
            name='release_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Месяц релиза'),
        ),
        migrations.AlterField(
            model_name='record',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год релиза'),
        ),
    ]
