# Generated by Django 5.1.7 on 2025-10-03 14:48

import records.models
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_record_is_expected_record_release_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('not specified', 'Not specified'), ('Electronic', 'Electronic')], max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='record',
            name='cover_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=records.models.PathByInstance('cover_image'), verbose_name='Record image'),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(choices=[('not specified', 'Not specified'), ('Bass Music', 'Bass Music'), ('Drum n Bass', 'Drum n Bass')], max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
