# Generated by Django 6.0 on 2026-02-20

from django.db import migrations, models, transaction


STYLE_NOT_SPECIFIED = "Not specified"
GENRE_UK_GARAGE = "UK Garage"
GENRE_GARAGE = "Garage"

NEW_CONDITION_NEW = "SS"
NEW_CONDITION_NOT_SPECIFIED = "NOT_SPECIFIED"


def _norm_vocab_key(value: str) -> str:
    return "".join(ch for ch in value.lower() if ch.isalnum())


def _merge_genres_uk_garage_into_garage(Genre, *, using: str) -> None:
    all_genres = list(Genre.objects.using(using).all().order_by("pk"))

    garage = next(
        (g for g in all_genres if _norm_vocab_key(str(g.name)) == "garage"),
        None,
    )

    uk_garage_list = [
        g for g in all_genres if _norm_vocab_key(str(g.name)) == "ukgarage"
    ]

    if garage is None and uk_garage_list:
        garage = uk_garage_list.pop(0)
        if garage.name != GENRE_GARAGE:
            garage.name = GENRE_GARAGE
            garage.save(update_fields=["name"])

    if garage is None:
        garage = Genre.objects.using(using).create(name=GENRE_GARAGE)

    for old_genre in uk_garage_list:
        if old_genre.pk == garage.pk:
            continue
        garage.records.add(*old_genre.records.using(using).all())
        old_genre.delete()

    for duplicate in Genre.objects.using(using).exclude(pk=garage.pk):
        if _norm_vocab_key(str(duplicate.name)) == "garage":
            garage.records.add(*duplicate.records.using(using).all())
            duplicate.delete()


def _ensure_not_specified_style_for_all_records(Style, Record, *, using: str) -> None:
    style = (
        Style.objects.using(using)
        .filter(name__iexact=STYLE_NOT_SPECIFIED)
        .order_by("pk")
        .first()
    )
    if style is None:
        style = Style.objects.using(using).create(name=STYLE_NOT_SPECIFIED)
    elif style.name != STYLE_NOT_SPECIFIED:
        style.name = STYLE_NOT_SPECIFIED
        style.save(update_fields=["name"])

    duplicates = (
        Style.objects.using(using)
        .filter(name__iexact=STYLE_NOT_SPECIFIED)
        .exclude(pk=style.pk)
    )
    for duplicate in duplicates:
        style.records.add(*duplicate.records.using(using).all())
        duplicate.delete()

    for record in Record.objects.using(using).all():
        record.styles.set([style])


def forwards(apps, schema_editor) -> None:
    Record = apps.get_model("records", "Record")
    Style = apps.get_model("records", "Style")
    Genre = apps.get_model("records", "Genre")
    using = schema_editor.connection.alias

    with transaction.atomic(using=using):
        Record.objects.using(using).update(condition=NEW_CONDITION_NEW)

        _ensure_not_specified_style_for_all_records(Style, Record, using=using)
        _merge_genres_uk_garage_into_garage(Genre, using=using)


def noop_reverse(apps, schema_editor) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0008_alter_record_availability_status_alter_record_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="condition",
            field=models.CharField(
                choices=[
                    ("SS", "НОВАЯ"),
                    ("M", "Mint (M)"),
                    ("NM", "Near Mint (NM)"),
                    ("VG+", "Very Good Plus (VG+)"),
                    ("VG", "Very Good (VG)"),
                    ("G+", "Good Plus (G+)"),
                    ("G", "Good (G)"),
                    ("F", "Fair (F)"),
                    ("P", "Poor (P)"),
                    ("NOT_SPECIFIED", "Не указано"),
                ],
                default="SS",
                max_length=20,
                verbose_name="Состояние",
            ),
        ),
        migrations.RunPython(forwards, reverse_code=noop_reverse),
    ]
