# Generated by Django 5.1.7 on 2025-10-03 14:59
from django.db import migrations

def prune_forward(apps, schema_editor):
    Genre = apps.get_model("records", "Genre")
    Style = apps.get_model("records", "Style")

    # !!! ВАЖНО: выбери .label или .value под свой реальный столбец (name/code/slug)
    # Ниже предполагаем, что в столбце name лежат "читаемые" названия, как в .label
    from records.models import GenreChoices, StyleChoices

    allowed_genres = {c.label for c in GenreChoices}
    allowed_styles = {c.label for c in StyleChoices}

    # Удаляем записи, которых нет в enum
    Genre.objects.exclude(name__in=allowed_genres).delete()
    Style.objects.exclude(name__in=allowed_styles).delete()

def prune_backward(apps, schema_editor):
    # Откат не восстанавливает удалённые записи
    pass

class Migration(migrations.Migration):
    dependencies = [
        ("records", "0009_alter_genre_name_alter_record_cover_image_and_more"),  # оставь как сгенерирует Django
    ]
    operations = [
        migrations.RunPython(prune_forward, prune_backward),
    ]

