# Generated by Django 6.0 on 2026-02-20 22:40

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0009_update_condition_and_vocab_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="vk_published_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Опубликовано в VK"
            ),
        ),
        migrations.CreateModel(
            name="VKPublicationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("IMMEDIATE", "Сразу"), ("SCHEDULED", "Отложено")],
                        db_index=True,
                        max_length=16,
                        verbose_name="Режим публикации",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Успех"), ("FAILED", "Ошибка")],
                        db_index=True,
                        max_length=16,
                        verbose_name="Статус публикации",
                    ),
                ),
                (
                    "planned_publish_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Запланировано на",
                    ),
                ),
                (
                    "effective_publish_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Фактическое время публикации",
                    ),
                ),
                (
                    "vk_post_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="ID поста VK"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="Текст ошибки"
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vk_publication_logs",
                        to="records.record",
                        verbose_name="Запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог публикации VK",
                "verbose_name_plural": "Логи публикаций VK",
                "ordering": ("-created",),
            },
        ),
    ]
