# Generated by Django 6.0 on 2026-03-15 23:48

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0010_record_vk_published_at_vkpublicationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordFormatEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(verbose_name="Порядок"),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Носитель"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Количество"
                    ),
                ),
                (
                    "format_name",
                    models.CharField(blank=True, max_length=64, verbose_name="Формат"),
                ),
                (
                    "details",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Дополнительно"
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_formats",
                        to="records.record",
                        verbose_name="Запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Структурированный формат релиза",
                "verbose_name_plural": "Структурированные форматы релиза",
                "ordering": ("record", "sort_order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("record", "sort_order"),
                        name="uq_recordformatentry_record_sort_order",
                    )
                ],
            },
        ),
    ]
