# Generated by Django 6.0 on 2026-03-05 22:47

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0010_record_vk_published_at_vkpublicationlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioEnrichmentJob",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("discogs_update", "Discogs update"),
                            ("manual_list", "Manual list action"),
                            ("manual_record", "Manual record form"),
                        ],
                        max_length=32,
                        verbose_name="Source",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "overwrite_existing",
                    models.BooleanField(
                        default=False, verbose_name="Overwrite existing"
                    ),
                ),
                (
                    "total_records",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total records"
                    ),
                ),
                (
                    "total_tracks",
                    models.PositiveIntegerField(default=0, verbose_name="Total tracks"),
                ),
                (
                    "updated_count",
                    models.PositiveIntegerField(default=0, verbose_name="Updated"),
                ),
                (
                    "skipped_count",
                    models.PositiveIntegerField(default=0, verbose_name="Skipped"),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, verbose_name="Errors"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Started at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Finished at"
                    ),
                ),
                (
                    "requested_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audio_enrichment_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio enrichment job",
                "verbose_name_plural": "Audio enrichment jobs",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="AudioEnrichmentJobRecord",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("already_running", "Already running"),
                            ("missing_source", "Missing source"),
                            ("validation_error", "Validation error"),
                        ],
                        default="",
                        max_length=64,
                        verbose_name="Reason code",
                    ),
                ),
                (
                    "updated_count",
                    models.PositiveIntegerField(default=0, verbose_name="Updated"),
                ),
                (
                    "skipped_count",
                    models.PositiveIntegerField(default=0, verbose_name="Skipped"),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, verbose_name="Errors"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Started at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Finished at"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_records",
                        to="records.audioenrichmentjob",
                        verbose_name="Job",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_enrichment_job_records",
                        to="records.record",
                        verbose_name="Record",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio enrichment job record",
                "verbose_name_plural": "Audio enrichment job records",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="AudioEnrichmentTrackResult",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("updated", "Updated"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("mismatch", "Mismatch"),
                            ("missing_youtube_url", "Missing YouTube URL"),
                            ("invalid_url", "Invalid URL"),
                            ("already_running", "Already running"),
                            ("download_error", "Download error"),
                            ("retry_exhausted", "Retry exhausted"),
                        ],
                        default="",
                        max_length=64,
                        verbose_name="Reason code",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Attempts",
                    ),
                ),
                (
                    "matched_title",
                    models.BooleanField(default=False, verbose_name="Matched title"),
                ),
                (
                    "matched_artist",
                    models.BooleanField(default=False, verbose_name="Matched artist"),
                ),
                (
                    "previous_audio_present",
                    models.BooleanField(
                        default=False, verbose_name="Previous audio present"
                    ),
                ),
                (
                    "final_audio_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="Final audio name",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="Error message"
                    ),
                ),
                (
                    "job_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_results",
                        to="records.audioenrichmentjobrecord",
                        verbose_name="Job record",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_enrichment_track_results",
                        to="records.track",
                        verbose_name="Track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio enrichment track result",
                "verbose_name_plural": "Audio enrichment track results",
                "ordering": ("created",),
            },
        ),
        migrations.AddConstraint(
            model_name="audioenrichmentjobrecord",
            constraint=models.UniqueConstraint(
                fields=("job", "record"), name="uq_audio_enrichment_job_record"
            ),
        ),
        migrations.AddConstraint(
            model_name="audioenrichmentjobrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "running"])),
                fields=("record",),
                name="uq_audio_enrichment_active_record",
            ),
        ),
        migrations.AddConstraint(
            model_name="audioenrichmenttrackresult",
            constraint=models.UniqueConstraint(
                fields=("job_record", "track"), name="uq_audio_enrichment_track_result"
            ),
        ),
    ]
