# Generated by Django 6.0 on 2026-04-01 22:23

import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models, transaction


LEGACY_FORMAT_LIBRARY = (
    "Not specified",
    '12" Vinyl',
    '2x12" Vinyl',
    '10" Vinyl',
    '7" Vinyl',
    '3x12" Vinyl',
    '4x12" Vinyl',
    '5x12" Vinyl',
)
DEFAULT_LEGACY_FORMAT = "Not specified"


def normalize_legacy_format_library(apps, schema_editor) -> None:
    Format = apps.get_model("records", "Format")
    Record = apps.get_model("records", "Record")
    using = schema_editor.connection.alias

    allowed_lookup = {name.casefold(): name for name in LEGACY_FORMAT_LIBRARY}

    with transaction.atomic(using=using):
        canonical_formats = {}
        for name in LEGACY_FORMAT_LIBRARY:
            obj, _ = Format.objects.using(using).get_or_create(name=name)
            canonical_formats[name] = obj

        default_format = canonical_formats[DEFAULT_LEGACY_FORMAT]

        for record in Record.objects.using(using).all():
            current_formats = list(record.formats.using(using).all())
            normalized_names: list[str] = []
            seen: set[str] = set()
            has_invalid_format = not current_formats

            for format_obj in current_formats:
                raw_name = str(getattr(format_obj, "name", "") or "").strip()
                canonical_name = allowed_lookup.get(raw_name.casefold())
                if canonical_name is None:
                    has_invalid_format = True
                    break

                canonical_key = canonical_name.casefold()
                if canonical_key in seen:
                    continue
                seen.add(canonical_key)
                normalized_names.append(canonical_name)

            if has_invalid_format or not normalized_names:
                record.formats.set([default_format])
                continue

            record.formats.set([canonical_formats[name] for name in normalized_names])

        Format.objects.using(using).exclude(name__in=LEGACY_FORMAT_LIBRARY).delete()


def set_active_structured_format_variant(apps, schema_editor) -> None:
    Record = apps.get_model("records", "Record")

    for record in Record.objects.all():
        variants = list(
            record.structured_formats.order_by("variant_of_format", "id").values_list(
                "variant_of_format",
                flat=True,
            )
        )
        record.active_structured_format_variant = variants[0] if variants else None
        record.save(update_fields=["active_structured_format_variant"])


def create_missing_audio_enrichment_schema(apps, schema_editor) -> None:
    """Создаёт отсутствующие audio-enrichment таблицы и constraints."""
    connection = schema_editor.connection
    introspection = connection.introspection
    model_names = (
        "AudioEnrichmentJob",
        "AudioEnrichmentJobRecord",
        "AudioEnrichmentTrackResult",
    )
    existing_tables = set(introspection.table_names())

    with connection.cursor() as cursor:
        for model_name in model_names:
            model = apps.get_model("records", model_name)
            table_name = model._meta.db_table
            created_table = False

            if table_name not in existing_tables:
                schema_editor.create_model(model)
                if model_name == "AudioEnrichmentJobRecord":
                    schema_editor.deferred_sql = [
                        statement
                        for statement in schema_editor.deferred_sql
                        if "uq_audio_enrichment_active_record" not in str(statement)
                    ]
                existing_tables.add(table_name)
                created_table = True

            if created_table:
                continue

            existing_columns = {
                column.name
                for column in introspection.get_table_description(cursor, table_name)
            }
            for field in model._meta.local_fields:
                if field.column in existing_columns:
                    continue
                schema_editor.add_field(model, field)
                existing_columns.add(field.column)

            existing_constraints = introspection.get_constraints(cursor, table_name)
            for constraint in model._meta.constraints:
                if constraint.name == "uq_audio_enrichment_active_record":
                    continue
                if constraint.name in existing_constraints:
                    continue
                schema_editor.add_constraint(model, constraint)
                existing_constraints[constraint.name] = {}

class Migration(migrations.Migration):

    replaces = [('records', '0011_recordformatentry'), ('records', '0012_normalize_legacy_format_library'), ('records', '0013_structuredformat_and_more'), ('records', '0015_reconcile_audio_enrichment_schema'), ('records', '0016_drop_legacy_audio_enrichment_match_columns'), ('records', '0017_youtubesessionstate'), ('records', '0018_alter_audioenrichmentjob_options_and_more'), ('records', '0019_alter_track_duration_alter_track_position_and_more'), ('records', '0020_alter_audioenrichmentjob_source'), ('records', '0021_vkpublicationjob_vkpublicationjobrecord'), ('records', '0022_track_audio_source'), ('records', '0023_alter_audioenrichmentjobrecord_options_and_more'), ('records', '0024_remove_audioenrichmentjobrecord_uq_audio_enrichment_active_record_and_more'), ('records', '0025_alter_vkpublicationjobrecord_options_and_more'), ('records', '0026_audioenrichmentjobrecord_admin_notification_shown_at_and_more'), ('records', '0027_alter_audioenrichmentjob_options_and_more'), ('records', '0028_rename_job_models'), ('records', '0029_alter_record_options_alter_recordsource_options_and_more'), ('records', '0030_vkpublicationreport_audio_failure_details')]

    dependencies = [
        ('records', '0010_record_vk_published_at_vkpublicationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordFormatEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sort_order', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                ('carrier', models.CharField(blank=True, max_length=64, verbose_name='Носитель')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('format_name', models.CharField(blank=True, max_length=64, verbose_name='Формат')),
                ('details', models.CharField(blank=True, max_length=255, verbose_name='Дополнительно')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_formats', to='records.record', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Структурированный формат релиза',
                'verbose_name_plural': 'Структурированные форматы релиза',
                'ordering': ('record', 'sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('record', 'sort_order'), name='uq_recordformatentry_record_sort_order')],
            },
        ),
        migrations.RunPython(
            code=normalize_legacy_format_library,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='record',
            name='active_structured_format_variant',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Активный вариант формата'),
        ),
        migrations.RenameModel(
            old_name='RecordFormatEntry',
            new_name='StructuredFormat',
        ),
        migrations.RenameField(
            model_name='structuredformat',
            old_name='sort_order',
            new_name='variant_of_format',
        ),
        migrations.AlterField(
            model_name='structuredformat',
            name='variant_of_format',
            field=models.PositiveSmallIntegerField(verbose_name='Вариант формата'),
        ),
        migrations.AlterModelOptions(
            name='structuredformat',
            options={'ordering': ('record', 'variant_of_format', 'id'), 'verbose_name': 'Структурированный формат релиза', 'verbose_name_plural': 'Структурированные форматы релиза'},
        ),
        migrations.RemoveConstraint(
            model_name='structuredformat',
            name='uq_recordformatentry_record_sort_order',
        ),
        migrations.AddConstraint(
            model_name='structuredformat',
            constraint=models.UniqueConstraint(fields=('record', 'variant_of_format'), name='uq_structuredformat_record_variant_of_format'),
        ),
        migrations.RunPython(
            code=set_active_structured_format_variant,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AudioEnrichmentJob',
                    fields=[
                        ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                        ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                        ('source', models.CharField(choices=[('discogs_import', 'Discogs import'), ('manual_list', 'Manual list action'), ('manual_record', 'Manual record form')], max_length=32, verbose_name='Source')),
                        ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed')], db_index=True, default='queued', max_length=32, verbose_name='Status')),
                        ('overwrite_existing', models.BooleanField(default=False, verbose_name='Overwrite existing')),
                        ('total_records', models.PositiveIntegerField(default=0, verbose_name='Records')),
                        ('total_tracks', models.PositiveIntegerField(default=0, verbose_name='Tracks')),
                        ('updated_count', models.PositiveIntegerField(default=0, verbose_name='Updated')),
                        ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Skipped')),
                        ('error_count', models.PositiveIntegerField(default=0, verbose_name='Errors')),
                        ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Started at')),
                        ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Finished at')),
                        ('requested_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_enrichment_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
                    ],
                    options={
                        'verbose_name': 'Audio enrichment job',
                        'verbose_name_plural': 'Audio enrichment jobs',
                        'ordering': ('-created',),
                    },
                ),
                migrations.CreateModel(
                    name='AudioEnrichmentJobRecord',
                    fields=[
                        ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                        ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=32, verbose_name='Status')),
                        ('reason_code', models.CharField(blank=True, choices=[('', 'None'), ('already_running', 'Already running'), ('validation_error', 'Validation error')], default='', max_length=64, verbose_name='Reason code')),
                        ('updated_count', models.PositiveIntegerField(default=0, verbose_name='Updated')),
                        ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Skipped')),
                        ('error_count', models.PositiveIntegerField(default=0, verbose_name='Errors')),
                        ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Started at')),
                        ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Finished at')),
                        ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_records', to='records.audioenrichmentjob', verbose_name='Job')),
                        ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_enrichment_job_records', to='records.record', verbose_name='Record')),
                    ],
                    options={
                        'verbose_name': 'Audio enrichment job record',
                        'verbose_name_plural': 'Audio enrichment job records',
                        'ordering': ('-created',),
                    },
                ),
                migrations.CreateModel(
                    name='AudioEnrichmentTrackResult',
                    fields=[
                        ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                        ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('updated', 'Updated'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=16, verbose_name='Status')),
                        ('reason_code', models.CharField(blank=True, choices=[('', 'None'), ('missing_youtube_url', 'Missing YouTube URL'), ('invalid_url', 'Invalid URL'), ('already_present', 'Already present'), ('download_error', 'Download error'), ('retry_exhausted', 'Retry exhausted')], default='', max_length=64, verbose_name='Reason code')),
                        ('attempts', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Attempts')),
                        ('previous_audio_present', models.BooleanField(default=False, verbose_name='Previous audio present')),
                        ('final_audio_name', models.CharField(blank=True, default='', max_length=512, verbose_name='Final audio name')),
                        ('error_message', models.TextField(blank=True, default='', verbose_name='Error message')),
                        ('job_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_results', to='records.audioenrichmentjobrecord', verbose_name='Job record')),
                        ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_enrichment_track_results', to='records.track', verbose_name='Track')),
                    ],
                    options={
                        'verbose_name': 'Audio enrichment track result',
                        'verbose_name_plural': 'Audio enrichment track results',
                        'ordering': ('created',),
                    },
                ),
                migrations.AddConstraint(
                    model_name='audioenrichmentjobrecord',
                    constraint=models.UniqueConstraint(fields=('job', 'record'), name='uq_audio_enrichment_job_record'),
                ),
                migrations.AddConstraint(
                    model_name='audioenrichmentjobrecord',
                    constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('record',), name='uq_audio_enrichment_active_record'),
                ),
                migrations.AddConstraint(
                    model_name='audioenrichmenttrackresult',
                    constraint=models.UniqueConstraint(fields=('job_record', 'track'), name='uq_audio_enrichment_track_result'),
                ),
            ],
        ),
        migrations.RunPython(
            code=create_missing_audio_enrichment_schema,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunSQL(
            sql='\n            ALTER TABLE records_audioenrichmenttrackresult\n            DROP COLUMN IF EXISTS matched_title,\n            DROP COLUMN IF EXISTS matched_artist;\n            ',
            reverse_sql='',
        ),
        migrations.CreateModel(
            name='YouTubeSessionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('auth_required', 'Authorization required'), ('login_in_progress', 'Login in progress')], db_index=True, default='unknown', max_length=32, verbose_name='Status')),
                ('status_message', models.TextField(blank=True, default='', verbose_name='Status message')),
                ('last_checked_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last checked at')),
                ('last_authenticated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last authenticated at')),
                ('last_error_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last error at')),
                ('last_login_started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last login started at')),
                ('last_login_finished_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last login finished at')),
            ],
            options={
                'verbose_name': 'YouTube session state',
                'verbose_name_plural': 'YouTube session state',
            },
        ),
        migrations.AlterModelOptions(
            name='audioenrichmentjob',
            options={'ordering': ('-created',), 'verbose_name': 'Задача по добавлению mp3 к трекам', 'verbose_name_plural': 'Задачи по добавлению mp3 к трекам'},
        ),
        migrations.AlterModelOptions(
            name='audioenrichmentjobrecord',
            options={'ordering': ('-created',), 'verbose_name': 'Элемент списка задач', 'verbose_name_plural': 'Список задач'},
        ),
        migrations.AlterModelOptions(
            name='audioenrichmenttrackresult',
            options={'ordering': ('created',), 'verbose_name': 'Результат добавления mp3 к трекам', 'verbose_name_plural': 'Результаты добавления mp3 к трекам'},
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(blank=True, help_text="Optional; e.g., '05:58'.", max_length=10, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='track',
            name='position',
            field=models.CharField(blank=True, help_text="Original position from the source (e.g., 'A1', 'B2'); may be empty.", max_length=10, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='track',
            name='position_index',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Sequential order across the release (1..N), independent of sides.', verbose_name='№ п.п.'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название трека'),
        ),
        migrations.AlterField(
            model_name='track',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional preview/video URL (e.g., YouTube).', max_length=512, null=True, verbose_name='Track URL'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='source',
            field=models.CharField(choices=[('discogs_import', 'Discogs import'), ('redeye_import', 'Redeye import'), ('redeye_manual_list', 'Redeye manual list action'), ('redeye_manual_record', 'Redeye manual record form'), ('manual_list', 'Manual list action'), ('manual_record', 'Manual record form')], max_length=32, verbose_name='Source'),
        ),
        migrations.CreateModel(
            name='VKPublicationJob',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual_list', 'Manual list action'), ('scheduled_list', 'Scheduled list action'), ('scheduled_single', 'Scheduled single record')], max_length=32, verbose_name='Source')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed')], db_index=True, default='queued', max_length=32, verbose_name='Status')),
                ('total_records', models.PositiveIntegerField(default=0, verbose_name='Records')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Success')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Skipped')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Errors')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Finished at')),
                ('requested_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vk_publication_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
            ],
            options={
                'verbose_name': 'Задача публикации в VK',
                'verbose_name_plural': 'Задачи публикации в VK',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='VKPublicationJobRecord',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('IMMEDIATE', 'Сразу'), ('SCHEDULED', 'Отложено')], db_index=True, max_length=16, verbose_name='Publication mode')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16, verbose_name='Status')),
                ('planned_publish_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Planned publish at')),
                ('effective_publish_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Effective publish at')),
                ('vk_post_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='VK post ID')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error message')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Finished at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_records', to='records.vkpublicationjob', verbose_name='Job')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vk_publication_job_records', to='records.record', verbose_name='Record')),
            ],
            options={
                'verbose_name': 'Элемент задачи публикации VK',
                'verbose_name_plural': 'Элементы задач публикации VK',
                'ordering': ('-created',),
                'constraints': [models.UniqueConstraint(fields=('job', 'record'), name='uq_vk_publication_job_record')],
            },
        ),
        migrations.AddField(
            model_name='track',
            name='audio_source',
            field=models.CharField(choices=[('unknown', 'Не указан'), ('youtube', 'YouTube'), ('bandcamp', 'Bandcamp'), ('redeye', 'Redeye')], default='unknown', max_length=16, verbose_name='Источник аудио'),
        ),
        migrations.AlterModelOptions(
            name='audioenrichmentjobrecord',
            options={'ordering': ('-created',), 'verbose_name': 'Лог добавления релиза и аудио', 'verbose_name_plural': 'Логи добавления релизов и аудио'},
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='audio_source_summary',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Источники аудио'),
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Текст ошибки'),
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='operation_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='queued_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Поставлено в очередь'),
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='release_source_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Источник релиза'),
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='result',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Итог'),
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='result_message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение итога'),
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='scope',
            field=models.CharField(choices=[('release', 'Релиз'), ('track', 'Трек')], db_index=True, default='release', max_length=16, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Этап'),
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='track_results_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Результаты по трекам'),
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='tracks_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Треков'),
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='warning_message',
            field=models.TextField(blank=True, default='', verbose_name='Текст предупреждения'),
        ),
        migrations.RemoveConstraint(
            model_name='audioenrichmentjobrecord',
            name='uq_audio_enrichment_active_record',
        ),
        migrations.AddConstraint(
            model_name='audioenrichmentjobrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running']), models.Q(('operation_name', 'Поиск аудио на YouTube'), _negated=True)), fields=('record',), name='uq_audio_enrichment_active_record'),
        ),
        migrations.AlterModelOptions(
            name='vkpublicationjobrecord',
            options={'ordering': ('-created',), 'verbose_name': 'Лог публикации VK', 'verbose_name_plural': 'Логи публикации VK'},
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='audio_expected_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ожидалось аудио'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='audio_failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Не загружено аудио'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='audio_source_summary',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Источники аудио'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='audio_uploaded_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Загружено аудио'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='failed_track_titles',
            field=models.JSONField(blank=True, default=list, verbose_name='Треки с проблемами'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='operation_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='photo_expected',
            field=models.BooleanField(default=False, verbose_name='Ожидалась загрузка изображения'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='photo_uploaded',
            field=models.BooleanField(default=False, verbose_name='Изображение загружено'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='queued_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Поставлено в очередь'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='release_source_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Источник релиза'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='result',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Итог'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='result_message',
            field=models.TextField(blank=True, default='', verbose_name='Описание результата'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Этап'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='warning_message',
            field=models.TextField(blank=True, default='', verbose_name='Предупреждение'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='effective_publish_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Фактическое время публикации'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Текст ошибки'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Завершено в'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='planned_publish_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Запланировано на'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Запущено'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='status',
            field=models.CharField(choices=[('queued', 'Ожидает выполнения'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('completed_with_warnings', 'Завершено с замечаниями'), ('failed', 'Завершено с ошибкой')], db_index=True, default='queued', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='vk_post_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID поста VK'),
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='admin_notification_shown_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Уведомление показано'),
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='notify_in_admin',
            field=models.BooleanField(default=False, verbose_name='Показывать уведомление в админке'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='admin_notification_shown_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Уведомление показано'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='notify_in_admin',
            field=models.BooleanField(default=False, verbose_name='Показывать уведомление в админке'),
        ),
        migrations.AlterModelOptions(
            name='audioenrichmentjob',
            options={'ordering': ('-created',), 'verbose_name': 'Задача обработки релиза', 'verbose_name_plural': 'Задачи обработки релизов'},
        ),
        migrations.AlterModelOptions(
            name='audioenrichmenttrackresult',
            options={'ordering': ('created',), 'verbose_name': 'Результат обработки аудио трека', 'verbose_name_plural': 'Результаты обработки аудио треков'},
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибок'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Завершено в'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='overwrite_existing',
            field=models.BooleanField(default=False, verbose_name='Перезаписывать существующее аудио'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='requested_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_enrichment_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Запросил'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Пропущено'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='source',
            field=models.CharField(choices=[('discogs_import', 'Импорт релиза из Discogs'), ('redeye_import', 'Импорт релиза из Redeye'), ('redeye_manual_list', 'Добавление аудио из Redeye для списка'), ('redeye_manual_record', 'Добавление аудио из Redeye для релиза'), ('manual_list', 'Добавление аудио по URL для списка'), ('manual_record', 'Добавление аудио по URL для релиза')], max_length=32, verbose_name='Источник операции'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Запущено'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Ожидает выполнения'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('completed_with_errors', 'Завершено с замечаниями'), ('failed', 'Завершено с ошибкой')], db_index=True, default='queued', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='total_records',
            field=models.PositiveIntegerField(default=0, verbose_name='Релизов'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='total_tracks',
            field=models.PositiveIntegerField(default=0, verbose_name='Треков'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='updated_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибок'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Завершено в'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_records', to='records.audioenrichmentjob', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('', 'Не указана'), ('already_running', 'Операция уже выполняется'), ('validation_error', 'Недостаточно данных для выполнения')], default='', max_length=64, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_enrichment_job_records', to='records.record', verbose_name='Релиз'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Пропущено'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Запущено'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='status',
            field=models.CharField(choices=[('queued', 'Ожидает выполнения'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('completed_with_errors', 'Завершено с замечаниями'), ('failed', 'Завершено с ошибкой'), ('skipped', 'Пропущено')], db_index=True, default='queued', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='updated_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Попыток'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Текст ошибки'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='final_audio_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Итоговое имя файла'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='job_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_results', to='records.audioenrichmentjobrecord', verbose_name='Лог операции'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='previous_audio_present',
            field=models.BooleanField(default=False, verbose_name='Аудио было прикреплено ранее'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('', 'Не указана'), ('missing_youtube_url', 'Отсутствует ссылка на YouTube или Bandcamp'), ('invalid_url', 'Ссылка на YouTube или Bandcamp не прошла валидацию'), ('already_present', 'Аудио уже прикреплено'), ('download_error', 'Ошибка загрузки аудио'), ('retry_exhausted', 'Попытки загрузки исчерпаны')], default='', max_length=64, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='status',
            field=models.CharField(choices=[('updated', 'Обновлено'), ('skipped', 'Пропущено'), ('failed', 'Ошибка')], max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_enrichment_track_results', to='records.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибок'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Завершено в'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='requested_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vk_publication_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Запросил'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Пропущено'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='source',
            field=models.CharField(choices=[('manual_list', 'Публикация выбранных релизов'), ('scheduled_list', 'Отложенная публикация списка релизов'), ('scheduled_single', 'Отложенная публикация одного релиза')], max_length=32, verbose_name='Источник операции'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Запущено'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Ожидает выполнения'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('completed_with_errors', 'Завершено с замечаниями'), ('failed', 'Завершено с ошибкой')], db_index=True, default='queued', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='success_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Успешно'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='total_records',
            field=models.PositiveIntegerField(default=0, verbose_name='Релизов'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_records', to='records.vkpublicationjob', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='mode',
            field=models.CharField(choices=[('IMMEDIATE', 'Сразу'), ('SCHEDULED', 'Отложено')], db_index=True, max_length=16, verbose_name='Режим публикации'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vk_publication_job_records', to='records.record', verbose_name='Релиз'),
        ),
        migrations.RenameModel(
            old_name='AudioEnrichmentJob',
            new_name='ReleaseJob',
        ),
        migrations.RenameModel(
            old_name='AudioEnrichmentJobRecord',
            new_name='ReleaseReport',
        ),
        migrations.RenameModel(
            old_name='VKPublicationJobRecord',
            new_name='VKPublicationReport',
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('title',), 'verbose_name': 'Релиз', 'verbose_name_plural': 'Релизы'},
        ),
        migrations.AlterModelOptions(
            name='recordsource',
            options={'verbose_name': 'Источник релиза', 'verbose_name_plural': 'Источники релиза'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('record', 'position_index', 'position'), 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterField(
            model_name='recordsource',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='records.record', verbose_name='Релиз'),
        ),
        migrations.AlterField(
            model_name='structuredformat',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_formats', to='records.record', verbose_name='Релиз'),
        ),
        migrations.AlterField(
            model_name='track',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='records.record', verbose_name='Релиз'),
        ),
        migrations.AlterField(
            model_name='vkpublicationlog',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vk_publication_logs', to='records.record', verbose_name='Релиз'),
        ),
        migrations.AddField(
            model_name='vkpublicationreport',
            name='audio_failure_details',
            field=models.JSONField(blank=True, default=list, verbose_name='Детали проблем по аудио'),
        ),
    ]
