# Generated by Django 5.1.7 on 2025-10-03 15:35
from django.db import migrations

GENRES = ["not specified", "Electronic"]
STYLES = ["not specified", "Bass Music", "Drum n Bass"]

def seed_forward(apps, schema_editor):
    Genre = apps.get_model("records", "Genre")
    Style = apps.get_model("records", "Style")

    # нормализуем имена по регистру для сравнения
    existing_genres = {n.lower(): n for n in Genre.objects.values_list("name", flat=True)}
    existing_styles = {n.lower(): n for n in Style.objects.values_list("name", flat=True)}

    # создать недостающие
    for name in GENRES:
        if name.lower() not in existing_genres:
            Genre.objects.create(name=name)
    for name in STYLES:
        if name.lower() not in existing_styles:
            Style.objects.create(name=name)

    # удалить лишние (в разработке можно смело)
    Genre.objects.exclude(name__in=GENRES).delete()
    Style.objects.exclude(name__in=STYLES).delete()

def seed_backward(apps, schema_editor):
    # откат: ничего не делаем
    pass

class Migration(migrations.Migration):
    dependencies = [
        ("records", "0011_alter_genre_name_alter_style_name"),  # ОСТАВЬ как сгенерировалось у тебя
    ]
    operations = [
        migrations.RunPython(seed_forward, seed_backward),
    ]
