# Generated by Django 5.1.7 on 2025-10-03 15:54
from django.db import migrations

def fix_not_specified(apps, schema_editor):
    Genre = apps.get_model("records", "Genre")
    Style = apps.get_model("records", "Style")

    # нормализуем все варианты "not specified" -> "Not specified"
    Genre.objects.filter(name__iexact="not specified").update(name="Not specified")
    Style.objects.filter(name__iexact="not specified").update(name="Not specified")

    # после этого удалим возможные дубликаты, оставив только один
    genres = list(Genre.objects.filter(name="Not specified").order_by("id"))
    if len(genres) > 1:
        # оставляем первый, остальные удаляем
        for g in genres[1:]:
            g.delete()

    styles = list(Style.objects.filter(name="Not specified").order_by("id"))
    if len(styles) > 1:
        for s in styles[1:]:
            s.delete()

def backwards(apps, schema_editor):
    # откат ничего не делает
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("records", "0012_seed_genres_styles"),  # подставь как у тебя
    ]

    operations = [
        migrations.RunPython(fix_not_specified, backwards),
    ]

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_seed_genres_styles'),
    ]

    operations = [
    ]
