# Generated by Django 5.1.7 on 2025-10-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_fix_not_specified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='name',
            field=models.CharField(choices=[('Not specified', 'Not specified'), ('7"', '7"'), ('10"', '10"'), ('12"', '12"'), ('EP', 'EP'), ('Single', 'Single'), ('LP', 'LP'), ('2LP', '2LP'), ('3LP', '3LP'), ('4LP', '4LP'), ('Box Set', 'Box Set'), ('Picture Disc', 'Picture Disc')], max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
