# Generated by Django 5.1.7 on 2025-10-03 16:51
from django.db import migrations


CANON = "Not specified"


def merge_ci(model_cls, through_cls, fk_name: str):
    """
    Склеивает case-insensitive дубликаты 'not specified' / 'Not specified'
    без нарушения UNIQUE(name).
    """
    # все кандидаты, не различающие регистр
    qs = model_cls.objects.filter(name__iexact="not specified").order_by("id")
    candidates = list(qs)
    if not candidates:
        return

    # хранитель: точный CANON, иначе самая старая запись
    keeper = next((x for x in candidates if x.name == CANON), candidates[0])
    victims = [x for x in candidates if x.id != keeper.id]
    if not victims:
        # один кандидат — просто привести к канону (если надо)
        if keeper.name != CANON:
            model_cls.objects.filter(id=keeper.id).update(name=CANON)
        return

    # Удалим возможные конфликтующие through-строки, затем переназначим остальные на keeper
    keeper_rec_ids = set(
        through_cls.objects.filter(**{fk_name: keeper}).values_list("record_id", flat=True)
    )

    for v in victims:
        if keeper_rec_ids:
            through_cls.objects.filter(
                **{fk_name + "_id": v.id, "record_id__in": keeper_rec_ids}
            ).delete()
        through_cls.objects.filter(**{fk_name + "_id": v.id}).update(**{fk_name + "_id": keeper.id})

    # Удаляем жертв
    model_cls.objects.filter(id__in=[v.id for v in victims]).delete()

    # Нормализуем имя хранителя
    if keeper.name != CANON:
        model_cls.objects.filter(id=keeper.id).update(name=CANON)


def forwards(apps, schema_editor):
    Genre = apps.get_model("records", "Genre")
    Style = apps.get_model("records", "Style")
    Record = apps.get_model("records", "Record")

    merge_ci(Genre, Record.genres.through, "genre")
    merge_ci(Style, Record.styles.through, "style")


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0015_merge_not_specified"),  # или последняя твоя миграция
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
