# Generated by Django 6.0 on 2026-03-17 17:05

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_drop_legacy_audio_enrichment_match_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeSessionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('auth_required', 'Authorization required'), ('login_in_progress', 'Login in progress')], db_index=True, default='unknown', max_length=32, verbose_name='Status')),
                ('status_message', models.TextField(blank=True, default='', verbose_name='Status message')),
                ('last_checked_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last checked at')),
                ('last_authenticated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last authenticated at')),
                ('last_error_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last error at')),
                ('last_login_started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last login started at')),
                ('last_login_finished_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last login finished at')),
            ],
            options={
                'verbose_name': 'YouTube session state',
                'verbose_name_plural': 'YouTube session state',
            },
        ),
    ]
