# Generated by Django 6.0 on 2026-03-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_youtubesessionstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioenrichmentjob',
            options={'ordering': ('-created',), 'verbose_name': 'Задача по добавлению mp3 к трекам', 'verbose_name_plural': 'Задачи по добавлению mp3 к трекам'},
        ),
        migrations.AlterModelOptions(
            name='audioenrichmentjobrecord',
            options={'ordering': ('-created',), 'verbose_name': 'Элемент списка задач', 'verbose_name_plural': 'Список задач'},
        ),
        migrations.AlterModelOptions(
            name='audioenrichmenttrackresult',
            options={'ordering': ('created',), 'verbose_name': 'Результат добавления mp3 к трекам', 'verbose_name_plural': 'Результаты добавления mp3 к трекам'},
        ),
    ]
