# Generated by Django 5.1.7 on 2025-10-05 15:07

import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_ci_unique_on_vocab_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('record', 'position_index', 'position'), 'verbose_name': 'Track', 'verbose_name_plural': 'Tracks'},
        ),
        migrations.RemoveConstraint(
            model_name='genre',
            name='genre_name_ci_unique',
        ),
        migrations.RemoveConstraint(
            model_name='style',
            name='style_name_ci_unique',
        ),
        migrations.AddField(
            model_name='track',
            name='audio_preview',
            field=models.FileField(blank=True, help_text='Local preview file stored in media (optional).', null=True, upload_to=records.models.PathByInstance('audio_preview'), verbose_name='Audio preview (MP3)'),
        ),
        migrations.AddField(
            model_name='track',
            name='position_index',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Sequential order across the release (1..N), independent of sides.', verbose_name='Order #'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(blank=True, help_text="Optional; e.g., '05:58'.", max_length=10, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='track',
            name='position',
            field=models.CharField(blank=True, help_text="Original position from the source (e.g., 'A1', 'B2'); may be empty.", max_length=10, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='track',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional preview/video URL (e.g., YouTube).', max_length=512, null=True, verbose_name='Track URL'),
        ),
    ]
