# Generated by Django 6.0 on 2026-03-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_alter_audioenrichmentjob_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(blank=True, help_text="Optional; e.g., '05:58'.", max_length=10, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='track',
            name='position',
            field=models.CharField(blank=True, help_text="Original position from the source (e.g., 'A1', 'B2'); may be empty.", max_length=10, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='track',
            name='position_index',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Sequential order across the release (1..N), independent of sides.', verbose_name='№ п.п.'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название трека'),
        ),
        migrations.AlterField(
            model_name='track',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional preview/video URL (e.g., YouTube).', max_length=512, null=True, verbose_name='Track URL'),
        ),
    ]
