# Generated by Django 6.0 on 2026-03-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_alter_track_duration_alter_track_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='source',
            field=models.CharField(choices=[('discogs_import', 'Discogs import'), ('redeye_import', 'Redeye import'), ('redeye_manual_list', 'Redeye manual list action'), ('redeye_manual_record', 'Redeye manual record form'), ('manual_list', 'Manual list action'), ('manual_record', 'Manual record form')], max_length=32, verbose_name='Source'),
        ),
    ]
