# Generated by Django 6.0 on 2026-03-29 09:39

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_alter_audioenrichmentjob_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VKPublicationJob',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual_list', 'Manual list action'), ('scheduled_list', 'Scheduled list action'), ('scheduled_single', 'Scheduled single record')], max_length=32, verbose_name='Source')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed')], db_index=True, default='queued', max_length=32, verbose_name='Status')),
                ('total_records', models.PositiveIntegerField(default=0, verbose_name='Records')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Success')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Skipped')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Errors')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Finished at')),
                ('requested_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vk_publication_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
            ],
            options={
                'verbose_name': 'Задача публикации в VK',
                'verbose_name_plural': 'Задачи публикации в VK',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='VKPublicationJobRecord',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('IMMEDIATE', 'Сразу'), ('SCHEDULED', 'Отложено')], db_index=True, max_length=16, verbose_name='Publication mode')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16, verbose_name='Status')),
                ('planned_publish_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Planned publish at')),
                ('effective_publish_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Effective publish at')),
                ('vk_post_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='VK post ID')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error message')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Finished at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_records', to='records.vkpublicationjob', verbose_name='Job')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vk_publication_job_records', to='records.record', verbose_name='Record')),
            ],
            options={
                'verbose_name': 'Элемент задачи публикации VK',
                'verbose_name_plural': 'Элементы задач публикации VK',
                'ordering': ('-created',),
                'constraints': [models.UniqueConstraint(fields=('job', 'record'), name='uq_vk_publication_job_record')],
            },
        ),
    ]
