# Generated by Django 6.0 on 2026-03-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_vkpublicationjob_vkpublicationjobrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_source',
            field=models.CharField(choices=[('unknown', 'Не указан'), ('youtube', 'YouTube'), ('bandcamp', 'Bandcamp'), ('redeye', 'Redeye')], default='unknown', max_length=16, verbose_name='Источник аудио'),
        ),
    ]
