# Generated by Django 6.0 on 2026-03-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0022_track_audio_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audioenrichmentjobrecord",
            options={
                "ordering": ("-created",),
                "verbose_name": "Лог добавления релиза и аудио",
                "verbose_name_plural": "Логи добавления релизов и аудио",
            },
        ),
        migrations.AddField(
            model_name="audioenrichmentjobrecord",
            name="audio_source_summary",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Источники аудио"
            ),
        ),
        migrations.AddField(
            model_name="audioenrichmentjobrecord",
            name="error_message",
            field=models.TextField(blank=True, default="", verbose_name="Текст ошибки"),
        ),
        migrations.AddField(
            model_name="audioenrichmentjobrecord",
            name="operation_name",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Операция"
            ),
        ),
        migrations.AddField(
            model_name="audioenrichmentjobrecord",
            name="queued_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Поставлено в очередь",
            ),
        ),
        migrations.AddField(
            model_name="audioenrichmentjobrecord",
            name="release_source_name",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Источник релиза"
            ),
        ),
        migrations.AddField(
            model_name="audioenrichmentjobrecord",
            name="result",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Итог"
            ),
        ),
        migrations.AddField(
            model_name="audioenrichmentjobrecord",
            name="result_message",
            field=models.TextField(
                blank=True, default="", verbose_name="Сообщение итога"
            ),
        ),
        migrations.AddField(
            model_name="audioenrichmentjobrecord",
            name="scope",
            field=models.CharField(
                choices=[("release", "Релиз"), ("track", "Трек")],
                db_index=True,
                default="release",
                max_length=16,
                verbose_name="Область",
            ),
        ),
        migrations.AddField(
            model_name="audioenrichmentjobrecord",
            name="stage",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Этап"
            ),
        ),
        migrations.AddField(
            model_name="audioenrichmentjobrecord",
            name="track_results_json",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Результаты по трекам"
            ),
        ),
        migrations.AddField(
            model_name="audioenrichmentjobrecord",
            name="tracks_total",
            field=models.PositiveIntegerField(default=0, verbose_name="Треков"),
        ),
        migrations.AddField(
            model_name="audioenrichmentjobrecord",
            name="warning_message",
            field=models.TextField(
                blank=True, default="", verbose_name="Текст предупреждения"
            ),
        ),
    ]
