# Generated by Django 6.0 on 2026-03-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_alter_audioenrichmentjobrecord_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='audioenrichmentjobrecord',
            name='uq_audio_enrichment_active_record',
        ),
        migrations.AddConstraint(
            model_name='audioenrichmentjobrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running']), models.Q(('operation_name', 'Поиск аудио на YouTube'), _negated=True)), fields=('record',), name='uq_audio_enrichment_active_record'),
        ),
    ]
