# Generated by Django 6.0 on 2026-03-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_remove_audioenrichmentjobrecord_uq_audio_enrichment_active_record_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vkpublicationjobrecord',
            options={'ordering': ('-created',), 'verbose_name': 'Лог публикации VK', 'verbose_name_plural': 'Логи публикации VK'},
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='audio_expected_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ожидалось аудио'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='audio_failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Не загружено аудио'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='audio_source_summary',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Источники аудио'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='audio_uploaded_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Загружено аудио'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='failed_track_titles',
            field=models.JSONField(blank=True, default=list, verbose_name='Треки с проблемами'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='operation_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='photo_expected',
            field=models.BooleanField(default=False, verbose_name='Ожидалась загрузка изображения'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='photo_uploaded',
            field=models.BooleanField(default=False, verbose_name='Изображение загружено'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='queued_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Поставлено в очередь'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='release_source_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Источник релиза'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='result',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Итог'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='result_message',
            field=models.TextField(blank=True, default='', verbose_name='Описание результата'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Этап'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='warning_message',
            field=models.TextField(blank=True, default='', verbose_name='Предупреждение'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='effective_publish_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Фактическое время публикации'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Текст ошибки'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Завершено в'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='planned_publish_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Запланировано на'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Запущено'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='status',
            field=models.CharField(choices=[('queued', 'Ожидает выполнения'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('completed_with_warnings', 'Завершено с замечаниями'), ('failed', 'Завершено с ошибкой')], db_index=True, default='queued', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='vk_post_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID поста VK'),
        ),
    ]
