# Generated by Django 6.0 on 2026-03-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0025_alter_vkpublicationjobrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='admin_notification_shown_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Уведомление показано'),
        ),
        migrations.AddField(
            model_name='audioenrichmentjobrecord',
            name='notify_in_admin',
            field=models.BooleanField(default=False, verbose_name='Показывать уведомление в админке'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='admin_notification_shown_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Уведомление показано'),
        ),
        migrations.AddField(
            model_name='vkpublicationjobrecord',
            name='notify_in_admin',
            field=models.BooleanField(default=False, verbose_name='Показывать уведомление в админке'),
        ),
    ]
