# Generated by Django 6.0 on 2026-03-29 16:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0026_audioenrichmentjobrecord_admin_notification_shown_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioenrichmentjob',
            options={'ordering': ('-created',), 'verbose_name': 'Задача обработки релиза', 'verbose_name_plural': 'Задачи обработки релизов'},
        ),
        migrations.AlterModelOptions(
            name='audioenrichmenttrackresult',
            options={'ordering': ('created',), 'verbose_name': 'Результат обработки аудио трека', 'verbose_name_plural': 'Результаты обработки аудио треков'},
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибок'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Завершено в'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='overwrite_existing',
            field=models.BooleanField(default=False, verbose_name='Перезаписывать существующее аудио'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='requested_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_enrichment_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Запросил'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Пропущено'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='source',
            field=models.CharField(choices=[('discogs_import', 'Импорт релиза из Discogs'), ('redeye_import', 'Импорт релиза из Redeye'), ('redeye_manual_list', 'Добавление аудио из Redeye для списка'), ('redeye_manual_record', 'Добавление аудио из Redeye для релиза'), ('manual_list', 'Добавление аудио по URL для списка'), ('manual_record', 'Добавление аудио по URL для релиза')], max_length=32, verbose_name='Источник операции'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Запущено'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Ожидает выполнения'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('completed_with_errors', 'Завершено с замечаниями'), ('failed', 'Завершено с ошибкой')], db_index=True, default='queued', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='total_records',
            field=models.PositiveIntegerField(default=0, verbose_name='Релизов'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='total_tracks',
            field=models.PositiveIntegerField(default=0, verbose_name='Треков'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjob',
            name='updated_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибок'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Завершено в'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_records', to='records.audioenrichmentjob', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('', 'Не указана'), ('already_running', 'Операция уже выполняется'), ('validation_error', 'Недостаточно данных для выполнения')], default='', max_length=64, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_enrichment_job_records', to='records.record', verbose_name='Релиз'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Пропущено'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Запущено'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='status',
            field=models.CharField(choices=[('queued', 'Ожидает выполнения'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('completed_with_errors', 'Завершено с замечаниями'), ('failed', 'Завершено с ошибкой'), ('skipped', 'Пропущено')], db_index=True, default='queued', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='audioenrichmentjobrecord',
            name='updated_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Попыток'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Текст ошибки'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='final_audio_name',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Итоговое имя файла'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='job_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_results', to='records.audioenrichmentjobrecord', verbose_name='Лог операции'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='previous_audio_present',
            field=models.BooleanField(default=False, verbose_name='Аудио было прикреплено ранее'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('', 'Не указана'), ('missing_youtube_url', 'Отсутствует ссылка на YouTube или Bandcamp'), ('invalid_url', 'Ссылка на YouTube или Bandcamp не прошла валидацию'), ('already_present', 'Аудио уже прикреплено'), ('download_error', 'Ошибка загрузки аудио'), ('retry_exhausted', 'Попытки загрузки исчерпаны')], default='', max_length=64, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='status',
            field=models.CharField(choices=[('updated', 'Обновлено'), ('skipped', 'Пропущено'), ('failed', 'Ошибка')], max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='audioenrichmenttrackresult',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_enrichment_track_results', to='records.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибок'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Завершено в'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='requested_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vk_publication_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Запросил'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Пропущено'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='source',
            field=models.CharField(choices=[('manual_list', 'Публикация выбранных релизов'), ('scheduled_list', 'Отложенная публикация списка релизов'), ('scheduled_single', 'Отложенная публикация одного релиза')], max_length=32, verbose_name='Источник операции'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Запущено'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Ожидает выполнения'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('completed_with_errors', 'Завершено с замечаниями'), ('failed', 'Завершено с ошибкой')], db_index=True, default='queued', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='success_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Успешно'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjob',
            name='total_records',
            field=models.PositiveIntegerField(default=0, verbose_name='Релизов'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_records', to='records.vkpublicationjob', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='mode',
            field=models.CharField(choices=[('IMMEDIATE', 'Сразу'), ('SCHEDULED', 'Отложено')], db_index=True, max_length=16, verbose_name='Режим публикации'),
        ),
        migrations.AlterField(
            model_name='vkpublicationjobrecord',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vk_publication_job_records', to='records.record', verbose_name='Релиз'),
        ),
    ]
