# Generated by Django 6.0 on 2026-03-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0028_rename_job_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('title',), 'verbose_name': 'Релиз', 'verbose_name_plural': 'Релизы'},
        ),
        migrations.AlterModelOptions(
            name='recordsource',
            options={'verbose_name': 'Источник релиза', 'verbose_name_plural': 'Источники релиза'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('record', 'position_index', 'position'), 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterField(
            model_name='recordsource',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='records.record', verbose_name='Релиз'),
        ),
        migrations.AlterField(
            model_name='structuredformat',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_formats', to='records.record', verbose_name='Релиз'),
        ),
        migrations.AlterField(
            model_name='track',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='records.record', verbose_name='Релиз'),
        ),
        migrations.AlterField(
            model_name='vkpublicationlog',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vk_publication_logs', to='records.record', verbose_name='Релиз'),
        ),
    ]
