# Generated by Django 6.0 on 2026-04-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0029_alter_record_options_alter_recordsource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkpublicationreport',
            name='audio_failure_details',
            field=models.JSONField(blank=True, default=list, verbose_name='Детали проблем по аудио'),
        ),
    ]
