"""
Django settings for dubplate-special-api project.

Generated by 'django-admin startproject' using Django 5.1.20.

For more information on this file, see:
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path

import environ

from config.logging import build_logging_config

# Initialize environment variables
env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Allows to keep applications in apps directory
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))

# ========================
# SECURITY CONFIGURATION
# ========================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", False)
# Hosts/domain names that this Django site can serve
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000
# Discogs token
DISCOGS_TOKEN = env("DISCOGS_API_KEY", default="")
# User Agent
DISCOGS_USER_AGENT = env("DISCOGS_USER_AGENT", default="dubplate-special/1.0")
# SMS Settings
SMS_API_KEY = env("SMS_API_KEY", default=None)
SMS_PROVIDER = env("SMS_PROVIDER", default="sms_ru")
SMS_TEST_MODE = env.bool("SMS_TEST_MODE", default=True)

# =====================
# APPLICATION DEFINITION
# =====================
INSTALLED_APPS = [
    # Django core apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "corsheaders",  # https://github.com/adamchainz/django-cors-headers
    "django_ckeditor_5",  # https://github.com/hvlads/django-ckeditor-5
    "django_extensions",  # https://django-extensions.readthedocs.io
    "django_filters",  # https://www.django-rest-framework.org/api-guide/filtering/
    "drf_spectacular",  # https://pypi.org/project/drf-spectacular/
    "rest_framework",  # https://www.django-rest-framework.org/
    "rest_framework.authtoken",  # Token authentication
    "solo",  # https://github.com/lazybird/django-solo
    "sorl.thumbnail",  # https://sorl-thumbnail.readthedocs.io/
    # Project apps
    "accounts",
    "core",
    "records",
    "orders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "core.middleware.AdminTooManyFieldsSentMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# SILK
SILK_ENABLED = env.bool("SILK_ENABLED", False)
if SILK_ENABLED:
    INSTALLED_APPS.append("silk")  # https://pypi.org/project/django-silk/
    MIDDLEWARE.insert(1, "silk.middleware.SilkyMiddleware")

    SILKY_AUTHENTICATION = True
    SILKY_AUTHORISATION = True

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# =============
# DATABASE
# =============
# Uses django-environ to automatically parse DB_* variables or DATABASE_URL
# DATABASES = {
#     "default": env.db(),
# }
RUN_ENV = os.getenv("RUN_ENV", "local")
POSTGRES_NAME = env("POSTGRES_DB")
POSTGRES_USER = env("POSTGRES_USER")
POSTGRES_PASSWORD = env("POSTGRES_PASSWORD")
POSTGRES_PORT = env("POSTGRES_PORT")

if RUN_ENV == "docker":
    POSTGRES_HOST = env("POSTGRES_HOST")
else:
    POSTGRES_HOST = "127.0.0.1"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "USER": POSTGRES_USER,
        "PASSWORD": POSTGRES_PASSWORD,
        "NAME": POSTGRES_NAME,
        "HOST": POSTGRES_HOST,
        "PORT": POSTGRES_PORT,
    }
}

# ======================
# PASSWORD VALIDATION
# ======================
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# =================
# INTERNATIONALIZATION
# =================
LANGUAGE_CODE = "en"
LANGUAGES = [
    ("en", "English"),
    ("ru", "Russian"),
]
TIME_ZONE = env("TIME_ZONE", default="Europe/Moscow")
USE_I18N = True
USE_L10N = True
USE_TZ = True
LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

# =================
# CELERY / REDIS
# =================
if RUN_ENV == "docker":
    CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://redis:6379/0")
    CELERY_RESULT_BACKEND = env(
        "CELERY_RESULT_BACKEND",
        default="redis://redis:6379/1",
    )
else:
    CELERY_BROKER_URL = env(
        "CELERY_BROKER_URL",
        default="redis://127.0.0.1:6379/0",
    )
    CELERY_RESULT_BACKEND = env(
        "CELERY_RESULT_BACKEND",
        default="redis://127.0.0.1:6379/1",
    )

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = env.int("CELERY_TASK_TIME_LIMIT", default=1800)
CELERY_TASK_SOFT_TIME_LIMIT = env.int("CELERY_TASK_SOFT_TIME_LIMIT", default=1500)

# =================
# YOUTUBE AUDIO ENRICHMENT
# =================
if RUN_ENV == "docker":
    YOUTUBE_BROWSER_PROFILE_DIR = env(
        "YOUTUBE_BROWSER_PROFILE_DIR",
        default="/app/runtime/youtube-browser-profile",
    )
    YOUTUBE_SESSION_LOCK_FILE = env(
        "YOUTUBE_SESSION_LOCK_FILE",
        default="/app/runtime/youtube-session-refresh.lock",
    )
    YOUTUBE_YTDLP_CACHE_DIR = env(
        "YOUTUBE_YTDLP_CACHE_DIR",
        default="/app/runtime/yt-dlp-cache",
    )
    YOUTUBE_JS_RUNTIME_PATH = env(
        "YOUTUBE_JS_RUNTIME_PATH",
        default="/usr/local/bin/deno",
    )
else:
    YOUTUBE_BROWSER_PROFILE_DIR = env(
        "YOUTUBE_BROWSER_PROFILE_DIR",
        default=str(BASE_DIR / "runtime" / "youtube-browser-profile"),
    )
    YOUTUBE_SESSION_LOCK_FILE = env(
        "YOUTUBE_SESSION_LOCK_FILE",
        default=str(BASE_DIR / "runtime" / "youtube-session-refresh.lock"),
    )
    YOUTUBE_YTDLP_CACHE_DIR = env(
        "YOUTUBE_YTDLP_CACHE_DIR",
        default=str(BASE_DIR / "runtime" / "yt-dlp-cache"),
    )
    YOUTUBE_JS_RUNTIME_PATH = env("YOUTUBE_JS_RUNTIME_PATH", default="")

YOUTUBE_JS_RUNTIME = env(
    "YOUTUBE_JS_RUNTIME",
    default="deno" if RUN_ENV == "docker" else "node",
)
YOUTUBE_BROWSER_NAME = env("YOUTUBE_BROWSER_NAME", default="chromium")
YOUTUBE_BROWSER_KEYRING = env(
    "YOUTUBE_BROWSER_KEYRING",
    default="BASICTEXT" if RUN_ENV == "docker" else "",
)
YOUTUBE_REMOTE_COMPONENTS = env.list(
    "YOUTUBE_REMOTE_COMPONENTS",
    default=["ejs:github"],
)
YOUTUBE_SESSION_REFRESH_URL = env(
    "YOUTUBE_SESSION_REFRESH_URL",
    default="https://www.youtube.com/",
)
YOUTUBE_SESSION_LOGIN_URL = env(
    "YOUTUBE_SESSION_LOGIN_URL",
    default="https://accounts.google.com/ServiceLogin?service=youtube",
)
YOUTUBE_SESSION_REFRESH_WAIT_MS = env.int(
    "YOUTUBE_SESSION_REFRESH_WAIT_MS",
    default=3_000,
)
YOUTUBE_SESSION_LOGIN_TIMEOUT_MS = env.int(
    "YOUTUBE_SESSION_LOGIN_TIMEOUT_MS",
    default=900_000,
)
YOUTUBE_SESSION_LOGIN_POLL_MS = env.int(
    "YOUTUBE_SESSION_LOGIN_POLL_MS",
    default=2_000,
)
YOUTUBE_SESSION_LOGIN_SUCCESS_WAIT_MS = env.int(
    "YOUTUBE_SESSION_LOGIN_SUCCESS_WAIT_MS",
    default=10_000,
)
YOUTUBE_SESSION_LOCK_WAIT_MS = env.int(
    "YOUTUBE_SESSION_LOCK_WAIT_MS",
    default=15_000,
)
YOUTUBE_SESSION_RECOVERY_RETRY_ENABLED = env.bool(
    "YOUTUBE_SESSION_RECOVERY_RETRY_ENABLED",
    default=True,
)
YOUTUBE_SESSION_UI_URL = env(
    "YOUTUBE_SESSION_UI_URL",
    default="http://localhost:6080/vnc.html?autoconnect=1&resize=scale",
)
YOUTUBE_LOGIN_EMAIL = env("YOUTUBE_LOGIN_EMAIL", default="")
YOUTUBE_LOGIN_PASSWORD = env("YOUTUBE_LOGIN_PASSWORD", default="")

# =============
# STATIC FILES
# =============
STATIC_URL = "static/"
# Note: STATIC_ROOT should be set when collecting static files for production
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# ====================
# DEFAULT PRIMARY KEY
# ====================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =================
# CUSTOM USER MODEL
# =================
AUTH_USER_MODEL = "accounts.User"

# =============
# MEDIA FILES
# =============
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# ===================
# CKEDITOR 5 CONFIG
# ===================
# Custom color palette for CKEditor
customColorPalette = [
    {"color": "hsl(4, 90%, 58%)", "label": "Red"},
    {"color": "hsl(340, 82%, 52%)", "label": "Pink"},
    {"color": "hsl(291, 64%, 42%)", "label": "Purple"},
    {"color": "hsl(262, 52%, 47%)", "label": "Deep Purple"},
    {"color": "hsl(231, 48%, 48%)", "label": "Indigo"},
    {"color": "hsl(207, 90%, 54%)", "label": "Blue"},
]

# CKEditor 5 configuration
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": {
            "items": [
                "heading",
                "|",
                "bold",
                "italic",
                "link",
                "bulletedList",
                "numberedList",
                "blockQuote",
                "imageUpload",
            ],
        }
    },
    "extends": {
        "blockToolbar": [
            "paragraph",
            "heading1",
            "heading2",
            "heading3",
            "|",
            "bulletedList",
            "numberedList",
            "|",
            "blockQuote",
        ],
        "toolbar": {
            "items": [
                "heading",
                "|",
                "outdent",
                "indent",
                "|",
                "bold",
                "italic",
                "link",
                "underline",
                "strikethrough",
                "code",
                "subscript",
                "superscript",
                "highlight",
                "|",
                "codeBlock",
                "sourceEditing",
                "insertImage",
                "bulletedList",
                "numberedList",
                "todoList",
                "|",
                "blockQuote",
                "imageUpload",
                "|",
                "fontSize",
                "fontFamily",
                "fontColor",
                "fontBackgroundColor",
                "mediaEmbed",
                "removeFormat",
                "insertTable",
            ],
            "shouldNotGroupWhenFull": True,
        },
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:alignLeft",
                "imageStyle:alignRight",
                "imageStyle:alignCenter",
                "imageStyle:side",
                "|",
            ],
            "styles": [
                "full",
                "side",
                "alignLeft",
                "alignRight",
                "alignCenter",
            ],
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableProperties",
                "tableCellProperties",
            ],
            "tableProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette,
            },
            "tableCellProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette,
            },
        },
        "heading": {
            "options": [
                {
                    "model": "paragraph",
                    "title": "Paragraph",
                    "class": "ck-heading_paragraph",
                },
                {
                    "model": "heading1",
                    "view": "h1",
                    "title": "Heading 1",
                    "class": "ck-heading_heading1",
                },
                {
                    "model": "heading2",
                    "view": "h2",
                    "title": "Heading 2",
                    "class": "ck-heading_heading2",
                },
                {
                    "model": "heading3",
                    "view": "h3",
                    "title": "Heading 3",
                    "class": "ck-heading_heading3",
                },
            ]
        },
    },
    "list": {
        "properties": {
            "styles": "true",
            "startIndex": "true",
            "reversed": "true",
        }
    },
}

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 18,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# Настройки CORS (Cross-Origin Resource Sharing)
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS")

# Разрешить куки и заголовки авторизации
CORS_ALLOW_CREDENTIALS = True

# Разрешенные методы (опционально, можно не указывать, так как по умолчанию разрешены безопасные методы)
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# Разрешенные заголовки (опционально)
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

APP_LOG_LEVEL = env("APP_LOG_LEVEL", default="INFO")
DJANGO_LOG_LEVEL = env("DJANGO_LOG_LEVEL", default="WARNING")
APP_LOG_FORMAT = env("APP_LOG_FORMAT", default="text")
APP_LOG_DESTINATION = env("APP_LOG_DESTINATION", default="stdout")
APP_LOG_COLOR = env("APP_LOG_COLOR", default="true" if DEBUG else "false")
APP_LOG_FILE_PATH = env(
    "APP_LOG_FILE_PATH",
    default=str(BASE_DIR / "logs" / "app.log"),
)

LOGGING = build_logging_config(
    app_level=APP_LOG_LEVEL,
    django_level=DJANGO_LOG_LEVEL,
    log_format=APP_LOG_FORMAT,
    destination=APP_LOG_DESTINATION,
    color=APP_LOG_COLOR,
    file_path=APP_LOG_FILE_PATH,
)

# VK интеграция

VK_GROUP_ID = int(os.getenv("VK_GROUP_ID", "0"))  # пример: -225812294
VK_ACCESS_TOKEN = os.getenv("VK_ACCESS_TOKEN", "")
